"""adding name col

Revision ID: 13997b14aaa2
Revises: e23c7b383158
Create Date: 2024-04-08 10:44:11.619459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13997b14aaa2'
down_revision = 'e23c7b383158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
