"""adding time to routine

Revision ID: cb3d77703c4a
Revises: c61e18d625b1
Create Date: 2024-04-29 10:48:15.802888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3d77703c4a'
down_revision = 'c61e18d625b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
